package com.nesa.core.scheduling

import com.nesa.core.model.Activity
import com.nesa.core.model.LifeSchedule
import com.nesa.core.model.NesaModule
import com.nesa.core.model.Recurrence
import com.nesa.core.model.RecurrenceFrequency
import com.nesa.core.model.ScheduleEntry
import java.time.Instant
import java.time.LocalDate

/**
 * Turns a life schedule into the activities it implies.
 *
 * A pure function, so what a schedule produces is something a test can pin
 * exactly rather than something that has to be observed on a device.
 *
 * ## Why the activity ids are derived rather than random
 *
 * Every entry maps to an activity whose id is built from the schedule and entry
 * ids — see [activityIdFor]. That makes applying a schedule **idempotent**: the
 * second application writes the same rows as the first rather than a duplicate
 * set, so a user who edits their work hours twice does not end up with two
 * Works on every Monday.
 *
 * It also makes removal exact. Turning a schedule off means deleting precisely
 * the ids it would generate — no prefix scan, no ownership column, and no risk
 * of deleting an activity the user created by hand that happens to be called
 * "Work". `RecurrenceMaterialiser` is already idempotent for the same reason and
 * on the same day-by-day basis; this is the same property one level up.
 */
object LifeScheduleApplier {

    /**
     * The activities a schedule implies. Empty when it is switched off.
     *
     * @param now stamped onto the activities so `updatedAt` is meaningful.
     *   Passed in rather than read from a clock, so the result is reproducible.
     */
    fun activitiesFor(schedule: LifeSchedule, now: Instant, from: LocalDate): List<Activity> {
        if (!schedule.enabled) return emptyList()
        return schedule.entries.map { entry -> activityFor(schedule, entry, now, from) }
    }

    /**
     * The ids a schedule owns, whether or not it is currently enabled.
     *
     * Used to clean up: disabling a schedule, or removing one entry from it,
     * means deleting exactly these and nothing else.
     */
    fun activityIdsFor(schedule: LifeSchedule): List<String> =
        schedule.entries.map { activityIdFor(schedule.id, it.id) }

    /**
     * Stable and derived, never random. See the class comment — this is what
     * makes applying a schedule idempotent and removing one exact.
     */
    fun activityIdFor(scheduleId: String, entryId: String): String = "$PREFIX$scheduleId:$entryId"

    /** True when an activity was generated by a schedule rather than by hand. */
    fun isScheduleOwned(activityId: String): Boolean = activityId.startsWith(PREFIX)

    private fun activityFor(
        schedule: LifeSchedule,
        entry: ScheduleEntry,
        now: Instant,
        from: LocalDate
    ): Activity = Activity(
        id = activityIdFor(schedule.id, entry.id),
        title = entry.title,
        // Tagged as LIFE so the timeline can tell a recurring commitment from
        // something the user added today, without inspecting the id.
        module = NesaModule.LIFE,
        duration = entry.duration,
        priority = entry.priority,
        flexibility = entry.flexibility,
        // The time the user chose is a *preference*, not a placement. A fixed
        // entry will sit here because its flexibility says so; a flexible one
        // may be moved by the scheduler, which is the point of marking it
        // flexible in the first place.
        preferredStart = entry.start,
        recurrence = Recurrence(
            frequency = RecurrenceFrequency.WEEKLY,
            daysOfWeek = entry.days,
            // Anchored to the day the schedule was applied, so a future
            // every-other-week rule counts from something real.
            startDate = from
        ),
        createdAt = now,
        updatedAt = now
    )

    /**
     * The `life:` namespace. Present in the id itself so that a row's origin is
     * obvious in a database dump, where there is no code to ask.
     */
    private const val PREFIX = "life:"
}
